# Project:   scalo
# File:      rustfmt.toml
# Purpose:   Rust formatter configuration
# Language:  TOML
#
# License:   Apache-2.0
# Copyright: (c) 2026 HYPERI PTY LIMITED

edition = "2024"
max_width = 100
tab_spaces = 4
use_small_heuristics = "Default"
