# Project:   scalo
# File:      .cargo/config.toml
# Purpose:   Cargo build configuration
# Language:  TOML
#
# License:   Apache-2.0
# Copyright: (c) 2026 HYPERI PTY LIMITED

[build]
rustflags = ["-D", "warnings"]

[alias]
xtask = "run --package xtask --"
